# Generated by Django 4.1.4 on 2022-12-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cellphont',
            field=models.IntegerField(verbose_name='Celular'),
        ),
    ]
