# Generated by Django 4.1.4 on 2022-12-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_project_cellphont'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.IntegerField(primary_key=True, serialize=False, verbose_name='No_registro')),
                ('name_complet', models.TextField(max_length=100, verbose_name='Nombre completo')),
                ('adreess', models.TextField(max_length=250, verbose_name='Domicilio')),
                ('cellphont', models.IntegerField(verbose_name='Celular')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('date_of_birth', models.DateTimeField(verbose_name=' Fecha de Nacimiento')),
                ('photo', models.ImageField(upload_to='foto', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Pelfiles',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
