# Generated by Django 4.1.4 on 2022-12-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.IntegerField(verbose_name='RFC')),
                ('name_company', models.CharField(max_length=100, verbose_name='Nombre compañia')),
                ('address', models.TextField(max_length=250, verbose_name='Domicilio')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='Correo Empresarial')),
                ('release_date', models.DateField(verbose_name=' Fecha de lanzamiento')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
    ]
